
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Erryza Nur Alif
 */
public class f_mahasiswa extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs, rsjurusan;
    private String host = "";
    private String sql = "";
    private String npm, nama, tanggallahir;

    /**
     * Creates new form f_mahasiswa
     */
    public f_mahasiswa() {
        initComponents();
        koneksi();
        tampilmahasiswa("SELECT * FROM t_mahasiswa");
        lebarKolom();
        kosongkan();
        txt_jk.setVisible(false);
        
    }

    public void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_jadwalmatakuliah", "root", "");
            //JOptionPane.showMessageDialog(rootPane,
            //    "Koneksi Berhasil Broooo");
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(rootPane,
            //      "Koneksi Gagal" + "\n"
            //    + e.getMessage());
        }

    }

    public void lebarKolom() {
        TableColumn column;
        gridmahasiswa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = gridmahasiswa.getColumnModel().getColumn(0);
        column.setPreferredWidth(50);
        column = gridmahasiswa.getColumnModel().getColumn(1);
        column.setPreferredWidth(80);
        column = gridmahasiswa.getColumnModel().getColumn(2);
        column.setPreferredWidth(150);
        column = gridmahasiswa.getColumnModel().getColumn(3);
        column.setPreferredWidth(100);
    }

    public void kosongkan() {
        txt_npm.setText("");
        txt_nama.setText("");
        jdtanggal.setDate(null);
    }


    public void tampilmahasiswa(String sql) {
        DefaultTableModel kolom = new DefaultTableModel();
        kolom.addColumn("No");
        kolom.addColumn("NPM");
        kolom.addColumn("Nama Mahasiswa");
        kolom.addColumn("Tanggal Lahir");
        kolom.addColumn("Jenis Kelamin");

        try {
            int i = 1;
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM t_mahasiswa");
            while (rs.next()) {
                kolom.addRow(new Object[]{
                    ("" + i++),
                    rs.getString(1), rs.getString(2),
                    rs.getString(3), rs.getString(4)
                });
                gridmahasiswa.setModel(kolom);
                //BtnTambah.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Gagal Tampil ke dalam GRID" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jdtanggal = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_npm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        P = new javax.swing.JRadioButton();
        L = new javax.swing.JRadioButton();
        txt_jk = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridmahasiswa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Data Mahasiswa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 660, 50));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 80, -1));
        jPanel1.add(jdtanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Tanggal Lahir");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, -1));
        jPanel1.add(txt_npm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 210, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("NPM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 80, -1));

        P.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(P);
        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel1.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        L.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(L);
        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel1.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));
        jPanel1.add(txt_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 360, 170));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Data Mahasiswa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("Informasi Buku"); // NOI18N

        gridmahasiswa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        gridmahasiswa.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        gridmahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridmahasiswa.setName(""); // NOI18N
        gridmahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridmahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(gridmahasiswa);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 700, 360));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 60, 740, 400));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btntambah.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.setOpaque(false);
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel2.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 330, -1));

        btnsimpan.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setOpaque(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 61, 80, -1));

        btnubah.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnubah.setText("Ubah");
        btnubah.setOpaque(false);
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });
        jPanel2.add(btnubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 73, -1));

        btnkeluar.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.setOpaque(false);
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 329, -1));

        btnbatal.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setOpaque(false);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 61, 70, -1));

        btnhapus.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setOpaque(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 61, 75, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 360, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridmahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridmahasiswaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gridmahasiswaMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        txt_npm.requestFocus();//Jika sudah di pilih btn tambah maka cursorr akan pindah ke txtid
        btntambah.setEnabled(false);//jika sudah di pilih btntambah maka btn tambah sudah tidak bisa di klik lagi
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
        btnbatal.setEnabled(true);
        kosongkan();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        npm = txt_npm.getText();
        nama = txt_nama.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yy-MM-dd");
        Date tanggal = new Date();
        tanggal = jdtanggal.getDate();
        String tgl_lahir = dateFormat.format(tanggal);
        String jk = txt_jk.getText();
        try {
            sql = "INSERT INTO t_mahasiswa"
                    + "(npm, nama, tgl_lahir"
                    + ",jenis_kelamin) VALUES "
                    + "('" + npm + "',"
                    + "'" + nama + "',"
                    + "'" + tgl_lahir + "',"
                    + "'" + jk + "')";

            st = con.createStatement();
            st.execute(sql);
            tampilmahasiswa("SELECT * FROM t_mahasiswa");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Menyimpan Data Mahasiswa");
            btnsimpan.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan Mohon Periksa Kembali Codingnya" + e.getMessage());
        } {
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        npm = txt_npm.getText();
        nama = txt_nama.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yy-MM-dd");
        Date tanggal = new Date();
        tanggal = jdtanggal.getDate();
        String tgl_lahir = dateFormat.format(tanggal);
        String jk = txt_jk.getText();
        try {
            sql = "UPDATE t_mahasiswa set npm='" + npm + "',"
                    + "nama='" + nama + "',"
                    + "tgl_lahir='" + tgl_lahir + "',"
                    + "jenis_kelamin='" + jk + "' "
                    + "WHERE npm='" + npm + "'";

            st = con.createStatement();
            st.execute(sql);
            tampilmahasiswa("SELECT * FROM t_mahasiswa");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Mengubah Data Mahasiswa");
            btnubah.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal DiUbah Mohon Periksa Kembali Codingnya" + e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int selectedoption = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar dari Aplikasi?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);
        if (selectedoption == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        btntambah.setEnabled(true);//Untuk mengaktifkan kembali tombol btntambah yang sudah di disable tadi
        btnhapus.setEnabled(true);
        btnubah.setEnabled(true);
        btntambah.requestFocus(); // jika sudah di klik btnbatal maka kursor akan berpindah ke btntambah
        kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        npm = txt_npm.getText(); // untuk memanggil id yang sudah di kenalkan di initcomponent
        try {
            sql = "DELETE FROM t_mahasiswa "
                    + "WHERE npm='" + npm + "'";

            st = con.createStatement();
            st.execute(sql);
            tampilmahasiswa("SELECT * FROM t_mahasiswa");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Menhapus Data Mahasiswa");
            btnhapus.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal DiHapus Mohon Periksa Kembali Codingnya" + e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        // TODO add your handling code here:
        txt_jk.setText("Laki-Laki");
    }//GEN-LAST:event_LActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        // TODO add your handling code here:
        txt_jk.setText("Perempuan");
    }//GEN-LAST:event_PActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton L;
    private javax.swing.JRadioButton P;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable gridmahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdtanggal;
    private javax.swing.JTextField txt_jk;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_npm;
    // End of variables declaration//GEN-END:variables
}
