import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erryza Nur Alif
 */
public class f_matakuliah extends javax.swing.JFrame {

    private Connection con;
    private Statement st;
    private ResultSet rs, rsmk;
    private String host = "";
    private String sql = "";
    private String id, nama, tanggallahir, mk, id_mk, alamat, nohp, sks;

    /**
     * Creates new form f_matakuliah
     */
    public f_matakuliah() {
        initComponents();
        koneksi();

        tampilmata_kuliah("SELECT * FROM t_matakuliah");
        kosongkan();
    }

    public void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_jadwalmatakuliah", "root", "");
            //JOptionPane.showMessageDialog(rootPane,
            //    "Koneksi Berhasil Broooo");
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(rootPane,
            //      "Koneksi Gagal" + "\n"
            //    + e.getMessage());
        }

    }

    public void kosongkan() {
        txt_id.setText("");
        txt_nama.setText("");
        txt_sks.setText("");

    }

    public void tampilmata_kuliah(String sql) {
        DefaultTableModel kolom = new DefaultTableModel();
        kolom.addColumn("No");
        kolom.addColumn("ID");
        kolom.addColumn("Nama Mata Kuliah");
        kolom.addColumn("SKS");

        try {
            int i = 1;
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM t_matakuliah");
            while (rs.next()) {
                kolom.addRow(new Object[]{
                    ("" + i++),
                    rs.getString(1), rs.getString(2), rs.getString(3)
                });
                GridItem.setModel(kolom);
                //BtnTambah.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,
                    "Gagal Tampil ke dalam GRID" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_sks = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GridItem = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btntambah = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 11))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Nama Matakuliah");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 180, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("SKS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, -1));
        jPanel1.add(txt_sks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 340, 120));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel3.setOpaque(false);

        jScrollPane1.setName("Informasi Buku"); // NOI18N

        GridItem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        GridItem.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        GridItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        GridItem.setName(""); // NOI18N
        GridItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GridItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(GridItem);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 380, 270));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel2.setOpaque(false);

        btntambah.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btntambah.setText("Tambah");
        btntambah.setOpaque(false);
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnsimpan.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setOpaque(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnubah.setText("Ubah");
        btnubah.setOpaque(false);
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnkeluar.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.setOpaque(false);
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setOpaque(false);
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Top Secret", 0, 12)); // NOI18N
        btnhapus.setText("Hapus");
        btnhapus.setOpaque(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsimpan)
                        .addGap(9, 9, 9)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus)
                    .addComponent(btnbatal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkeluar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 150));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setText("Data Matakuliah");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 370, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GridItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GridItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GridItemMouseClicked

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        txt_id.requestFocus();//Jika sudah di pilih btn tambah maka cursorr akan pindah ke txtid
        btntambah.setEnabled(false);//jika sudah di pilih btntambah maka btn tambah sudah tidak bisa di klik lagi
        btnsimpan.setEnabled(true);
        btnubah.setEnabled(false);
        btnhapus.setEnabled(false);
        btnbatal.setEnabled(true);
        kosongkan();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        id = txt_id.getText();
        nama = txt_nama.getText();
        sks = txt_sks.getText();

        try {
            sql = "INSERT INTO t_matakuliah"
                    + "(id_matkul, matkul, sks ) VALUES "
                    + "('" + id + "',"
                    + "'" + nama + "',"
                    + "'" + sks + "')";

            st = con.createStatement();
            st.execute(sql);
            tampilmata_kuliah("SELECT * FROM t_matakuliah");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Menyimpan Data Mata Kuliah");
            btnsimpan.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal Disimpan Mohon Periksa Kembali Codingnya" + e.getMessage());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        id = txt_id.getText();
        nama = txt_nama.getText();
        sks = txt_sks.getText();

        try {
            sql = "UPDATE t_matakuliah set id_matkul='" + id + "',"
                    + "matkul='" + nama + "',"
                    + "sks='" + sks + "'"
                    + "WHERE id_matkul='" + id + "'";

            st = con.createStatement();
            st.execute(sql);
            tampilmata_kuliah("SELECT * FROM t_matakuliah");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Mengubah Data Mata Kuliah");
            btnubah.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal DiUbah Mohon Periksa Kembali Codingnya" + e.getMessage());
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
        int selectedoption = JOptionPane.showConfirmDialog(null, "Apakah Anda Ingin Keluar dari Aplikasi?", "Tutup Aplikasi",
                JOptionPane.YES_NO_OPTION);
        if (selectedoption == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        btntambah.setEnabled(true);//Untuk mengaktifkan kembali tombol btntambah yang sudah di disable tadi
        btnhapus.setEnabled(true);
        btnubah.setEnabled(true);
        btntambah.requestFocus(); // jika sudah di klik btnbatal maka kursor akan berpindah ke btntambah
        kosongkan();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        id = txt_id.getText(); // untuk memanggil id yang sudah di kenalkan di initcomponent
        try {
            sql = "DELETE FROM t_matakuliah "
                    + "WHERE id_matkul='" + id + "'";

            st = con.createStatement();
            st.execute(sql);
            tampilmata_kuliah("SELECT * FROM t_matakuliah");
            JOptionPane.showMessageDialog(rootPane, "Selamat Anda Berhasil Menghapus Data Mata Kuliah");
            btnhapus.setEnabled(false);
            btntambah.setEnabled(true);
            kosongkan();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data Gagal DiHapus Mohon Periksa Kembali Codingnya" + e.getMessage());
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_matakuliah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_matakuliah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable GridItem;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkeluar;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_sks;
    // End of variables declaration//GEN-END:variables
}
